//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.PocketCiTray {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.PocketCiTray.CommonStrings", typeof(CommonStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Scout.
        /// </summary>
        internal static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server could not be contacted.
        /// </summary>
        internal static string HttpServerResponseConnection {
            get {
                return ResourceManager.GetString("HttpServerResponseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is a problem with the network connection.
        /// </summary>
        internal static string HttpServerResponseNetwork {
            get {
                return ResourceManager.GetString("HttpServerResponseNetwork", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The is an issue with the server&apos;s SSLcertificate.
        /// </summary>
        internal static string HttpServerResponseSslError {
            get {
                return ResourceManager.GetString("HttpServerResponseSslError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned: {0:G}.
        /// </summary>
        internal static string HttpServerResponseStatusError {
            get {
                return ResourceManager.GetString("HttpServerResponseStatusError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The response timed out.
        /// </summary>
        internal static string HttpServerResponseTimedOutError {
            get {
                return ResourceManager.GetString("HttpServerResponseTimedOutError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The server returned an unsupported response.
        /// </summary>
        internal static string HttpServerUnexpectedResponse {
            get {
                return ResourceManager.GetString("HttpServerUnexpectedResponse", resourceCulture);
            }
        }
    }
}
