//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.PocketCiTray {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
#if PSEUDOLOCALIZER_ENABLED
                    global::System.Resources.ResourceManager temp =
                        new Delay.PseudoLocalizerResourceManager("RichardSzalay.PocketCiTray.SettingsStrings", typeof(SettingsStrings).Assembly);
#else
                        global::System.Resources.ResourceManager temp =
                            new global::System.Resources.ResourceManager("RichardSzalay.PocketCiTray.SettingsStrings", typeof(SettingsStrings).Assembly);
#endif
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background Updates.
        /// </summary>
        public static string BackgroundUpdates {
            get {
                return ResourceManager.GetString("BackgroundUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change application and tile colours.
        /// </summary>
        public static string ColoursDescription {
            get {
                return ResourceManager.GetString("ColoursDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to change application colours.
        /// </summary>
        public static string ColoursLowEndDeviceDescription {
            get {
                return ResourceManager.GetString("ColoursLowEndDeviceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colours.
        /// </summary>
        public static string ColoursTitle {
            get {
                return ResourceManager.GetString("ColoursTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to disabled.
        /// </summary>
        public static string Disabled {
            get {
                return ResourceManager.GetString("Disabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to enabled.
        /// </summary>
        public static string Enabled {
            get {
                return ResourceManager.GetString("Enabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End notifications.
        /// </summary>
        public static string EndNotificationsLabel {
            get {
                return ResourceManager.GetString("EndNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to every {0}.
        /// </summary>
        public static string EveryInterval {
            get {
                return ResourceManager.GetString("EveryInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed.
        /// </summary>
        public static string FailedLabel {
            get {
                return ResourceManager.GetString("FailedLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground Updates.
        /// </summary>
        public static string ForegroundUpdates {
            get {
                return ResourceManager.GetString("ForegroundUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins.
        /// </summary>
        public static string MinsFormat {
            get {
                return ResourceManager.GetString("MinsFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to all changes.
        /// </summary>
        public static string NotificationAllChanges {
            get {
                return ResourceManager.GetString("NotificationAllChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification days.
        /// </summary>
        public static string NotificationDaysLabel {
            get {
                return ResourceManager.GetString("NotificationDaysLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string NotificationFailed {
            get {
                return ResourceManager.GetString("NotificationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fixed.
        /// </summary>
        public static string NotificationFixed {
            get {
                return ResourceManager.GetString("NotificationFixed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to none.
        /// </summary>
        public static string NotificationNone {
            get {
                return ResourceManager.GetString("NotificationNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , .
        /// </summary>
        public static string NotificationSeparator {
            get {
                return ResourceManager.GetString("NotificationSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string NotificationTitle {
            get {
                return ResourceManager.GetString("NotificationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable.
        /// </summary>
        public static string NotificationUnavailable {
            get {
                return ResourceManager.GetString("NotificationUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min.
        /// </summary>
        public static string OneMin {
            get {
                return ResourceManager.GetString("OneMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue to update when phone is locked.
        /// </summary>
        public static string RunUnderLockScreen {
            get {
                return ResourceManager.GetString("RunUnderLockScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to foreground {0}, background {1}.
        /// </summary>
        public static string ScheduleDescriptionFormat {
            get {
                return ResourceManager.GetString("ScheduleDescriptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schedule.
        /// </summary>
        public static string ScheduleTitle {
            get {
                return ResourceManager.GetString("ScheduleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string SettingsTitle {
            get {
                return ResourceManager.GetString("SettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SETTINGS.
        /// </summary>
        public static string SettingsTitleUpper {
            get {
                return ResourceManager.GetString("SettingsTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start notifications.
        /// </summary>
        public static string StartNotificationsLabel {
            get {
                return ResourceManager.GetString("StartNotificationsLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful.
        /// </summary>
        public static string SuccessfulLabel {
            get {
                return ResourceManager.GetString("SuccessfulLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        public static string UnavailableLabel {
            get {
                return ResourceManager.GetString("UnavailableLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply to live tiles.
        /// </summary>
        public static string UseColoredLiveTilesLabel {
            get {
                return ResourceManager.GetString("UseColoredLiveTilesLabel", resourceCulture);
            }
        }
    }
}
