//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.PocketCiTray {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.PocketCiTray.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {1:hh:mm}.
        /// </summary>
        internal static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the status of build jobs in the background and notifies you of broken builds..
        /// </summary>
        internal static string BackgroundUpdateAgentDescription {
            get {
                return ResourceManager.GetString("BackgroundUpdateAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        internal static string BuildResult_Failed {
            get {
                return ResourceManager.GetString("BuildResult_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful.
        /// </summary>
        internal static string BuildResult_Success {
            get {
                return ResourceManager.GetString("BuildResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable.
        /// </summary>
        internal static string BuildResult_Unavailable {
            get {
                return ResourceManager.GetString("BuildResult_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enable job status updates while the application is not running? You can change this setting at any time in Settings..
        /// </summary>
        internal static string EnableBackgroundTaskPrompt {
            get {
                return ResourceManager.GetString("EnableBackgroundTaskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating build server.
        /// </summary>
        internal static string ErrorValidatingBuildServer {
            get {
                return ResourceManager.GetString("ErrorValidatingBuildServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        internal static string LessThanOneMinuteAgo {
            get {
                return ResourceManager.GetString("LessThanOneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins ago.
        /// </summary>
        internal static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {1:d}.
        /// </summary>
        internal static string OnDate {
            get {
                return ResourceManager.GetString("OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min ago.
        /// </summary>
        internal static string OneMinuteAgo {
            get {
                return ResourceManager.GetString("OneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM.
        /// </summary>
        internal static string ShortDatePattern {
            get {
                return ResourceManager.GetString("ShortDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {1:ddd}.
        /// </summary>
        internal static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        internal static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
