//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.261
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RichardSzalay.PocketCiTray {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RichardSzalay.PocketCiTray.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add server.
        /// </summary>
        public static string AddBuildServerTitle {
            get {
                return ResourceManager.GetString("AddBuildServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Build Scout.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to build scout.
        /// </summary>
        public static string ApplicationTitleLower {
            get {
                return ResourceManager.GetString("ApplicationTitleLower", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BUILD SCOUT.
        /// </summary>
        public static string ApplicationTitleUpper {
            get {
                return ResourceManager.GetString("ApplicationTitleUpper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to at {1:hh:mm}.
        /// </summary>
        public static string AtTime {
            get {
                return ResourceManager.GetString("AtTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates the status of build jobs in the background and notifies you of broken builds..
        /// </summary>
        public static string BackgroundUpdateAgentDescription {
            get {
                return ResourceManager.GetString("BackgroundUpdateAgentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blue.
        /// </summary>
        public static string BlueAccentBrush {
            get {
                return ResourceManager.GetString("BlueAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to brown.
        /// </summary>
        public static string BrownAccentBrush {
            get {
                return ResourceManager.GetString("BrownAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to failed.
        /// </summary>
        public static string BuildResult_Failed {
            get {
                return ResourceManager.GetString("BuildResult_Failed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to successful.
        /// </summary>
        public static string BuildResult_Success {
            get {
                return ResourceManager.GetString("BuildResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unavailable.
        /// </summary>
        public static string BuildResult_Unavailable {
            get {
                return ResourceManager.GetString("BuildResult_Unavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        public static string BuildStatusLabelSeperator {
            get {
                return ResourceManager.GetString("BuildStatusLabelSeperator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete build server?.
        /// </summary>
        public static string DeleteBuildServerConfirmationDescription {
            get {
                return ResourceManager.GetString("DeleteBuildServerConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All related jobs will be removed, but will remain on the server.
        /// </summary>
        public static string DeleteBuildServerConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteBuildServerConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete job?.
        /// </summary>
        public static string DeleteJobConfirmationDescription {
            get {
                return ResourceManager.GetString("DeleteJobConfirmationDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The job will remain on the server.
        /// </summary>
        public static string DeleteJobConfirmationMessage {
            get {
                return ResourceManager.GetString("DeleteJobConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to colours.
        /// </summary>
        public static string EditColourSettingsTitle {
            get {
                return ResourceManager.GetString("EditColourSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notifications.
        /// </summary>
        public static string EditNoficiationSettingsTitle {
            get {
                return ResourceManager.GetString("EditNoficiationSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to schedule.
        /// </summary>
        public static string EditScheduleSettingsTitle {
            get {
                return ResourceManager.GetString("EditScheduleSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to settings.
        /// </summary>
        public static string EditSettingsTitle {
            get {
                return ResourceManager.GetString("EditSettingsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Would you like to enable job status updates while the application is not running? You can change this setting at any time in Settings..
        /// </summary>
        public static string EnableBackgroundTaskPrompt {
            get {
                return ResourceManager.GetString("EnableBackgroundTaskPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error validating build server.
        /// </summary>
        public static string ErrorValidatingBuildServer {
            get {
                return ResourceManager.GetString("ErrorValidatingBuildServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to finding jobs.
        /// </summary>
        public static string FindingJobsStatusMessage {
            get {
                return ResourceManager.GetString("FindingJobsStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gray.
        /// </summary>
        public static string GrayAccentBrush {
            get {
                return ResourceManager.GetString("GrayAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to green.
        /// </summary>
        public static string GreenAccentBrush {
            get {
                return ResourceManager.GetString("GreenAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to just now.
        /// </summary>
        public static string LessThanOneMinuteAgo {
            get {
                return ResourceManager.GetString("LessThanOneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lime.
        /// </summary>
        public static string LimeAccentBrush {
            get {
                return ResourceManager.GetString("LimeAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jobs.
        /// </summary>
        public static string ListJobsTitle {
            get {
                return ResourceManager.GetString("ListJobsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to loading.
        /// </summary>
        public static string LoadingStatusMessage {
            get {
                return ResourceManager.GetString("LoadingStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to magenta.
        /// </summary>
        public static string MagentaAccentBrush {
            get {
                return ResourceManager.GetString("MagentaAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to mango.
        /// </summary>
        public static string MangoAccentBrush {
            get {
                return ResourceManager.GetString("MangoAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} mins ago.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string NotificationNoneSelectedOption {
            get {
                return ResourceManager.GetString("NotificationNoneSelectedOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {1:d}.
        /// </summary>
        public static string OnDate {
            get {
                return ResourceManager.GetString("OnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 min ago.
        /// </summary>
        public static string OneMinuteAgo {
            get {
                return ResourceManager.GetString("OneMinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to theme color.
        /// </summary>
        public static string PhoneAccentBrush {
            get {
                return ResourceManager.GetString("PhoneAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pink.
        /// </summary>
        public static string PinkAccentBrush {
            get {
                return ResourceManager.GetString("PinkAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to purple.
        /// </summary>
        public static string PurpleAccentBrush {
            get {
                return ResourceManager.GetString("PurpleAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to red.
        /// </summary>
        public static string RedAccentBrush {
            get {
                return ResourceManager.GetString("RedAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select server.
        /// </summary>
        public static string SelectBuildServerTitle {
            get {
                return ResourceManager.GetString("SelectBuildServerTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to dd/MM.
        /// </summary>
        public static string ShortDatePattern {
            get {
                return ResourceManager.GetString("ShortDatePattern", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to teal.
        /// </summary>
        public static string TealAccentBrush {
            get {
                return ResourceManager.GetString("TealAccentBrush", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on {1:ddd}.
        /// </summary>
        public static string ThisWeek {
            get {
                return ResourceManager.GetString("ThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 day.
        /// </summary>
        public static string UpdateIntervalDay {
            get {
                return ResourceManager.GetString("UpdateIntervalDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} day.
        /// </summary>
        public static string UpdateIntervalDays {
            get {
                return ResourceManager.GetString("UpdateIntervalDays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 hour.
        /// </summary>
        public static string UpdateIntervalHour {
            get {
                return ResourceManager.GetString("UpdateIntervalHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} hours.
        /// </summary>
        public static string UpdateIntervalHours {
            get {
                return ResourceManager.GetString("UpdateIntervalHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 minute.
        /// </summary>
        public static string UpdateIntervalMinute {
            get {
                return ResourceManager.GetString("UpdateIntervalMinute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minutes.
        /// </summary>
        public static string UpdateIntervalMinutes {
            get {
                return ResourceManager.GetString("UpdateIntervalMinutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to never.
        /// </summary>
        public static string UpdateIntervalNever {
            get {
                return ResourceManager.GetString("UpdateIntervalNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to updating.
        /// </summary>
        public static string UpdatingStatusMessage {
            get {
                return ResourceManager.GetString("UpdatingStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to validating.
        /// </summary>
        public static string ValidatingBuildServerStatusMessage {
            get {
                return ResourceManager.GetString("ValidatingBuildServerStatusMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to yesterday.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
    }
}
