// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:1.8.1.0
//      SpecFlow Generator Version:1.8.0.0
//      Runtime Version:4.0.30319.239
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace RichardSzalay.PocketCiTray.AcceptanceTest.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "1.8.1.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("Add Cruise Project")]
    public partial class AddCruiseProjectFeature
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddCruiseProject.feature"
#line hidden
        
        [NUnit.Framework.TestFixtureSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "Add Cruise Project", "In order to know how my jobs are doing\r\nAs a developer\r\nI want to monitor the sta" +
                    "te of a cruise job", ProgrammingLanguage.CSharp, ((string[])(null)));
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.TestFixtureTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add Successful")]
        public virtual void AddSuccessful()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add Successful", ((string[])(null)));
#line 6
this.ScenarioSetup(scenarioInfo);
#line 7
 testRunner.Given("I have a build server called \"buildServer\"");
#line 8
 testRunner.And("the build server has a job called \"job1\"");
#line 9
 testRunner.And("my app is clean installed and running");
#line 10
 testRunner.When("I add a new build server \"buildServer\"");
#line 11
 testRunner.And("I add the \"job1\" job");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Failed")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void Failed()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Failed", new string[] {
                        "Ignore"});
#line 14
this.ScenarioSetup(scenarioInfo);
#line 15
 testRunner.Given("I have a build server called \"buildServer\"");
#line 16
 testRunner.And("the build server has a job called \"job1\"");
#line 17
 testRunner.And("the job\'s last run failed");
#line 18
 testRunner.And("I am monitoring the job");
#line 19
 testRunner.When("I view the status of my jobs");
#line 20
 testRunner.Then("the result should indicate the job failed");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Unavailable")]
        [NUnit.Framework.IgnoreAttribute()]
        public virtual void Unavailable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Unavailable", new string[] {
                        "Ignore"});
#line 23
this.ScenarioSetup(scenarioInfo);
#line 24
 testRunner.Given("I have a build server called \"buildServer\"");
#line 25
 testRunner.And("the build server has a job called \"job1\"");
#line 26
 testRunner.And("the build server is unavailable");
#line 27
 testRunner.And("I am monitoring the job");
#line 28
 testRunner.When("I view the status of my jobs");
#line 29
 testRunner.Then("the result should indicate the job is unavailable");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
